import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Image from 'next/image'
import { Button, Spacer } from '@chakra-ui/react'
import Projects from './Projects'
import Experience from './experience'

const inter = Inter({ subsets: ['latin'] })

export default function Home({users}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div style={{border:"1px solid red",padding:"10px" ,width:"300px" ,paddingLeft:"50px"}}>

{
    users.map((item)=>(
       <>
       
      <div>
      <img  style={{borderRadius:"50%",width:"100px"} } src={item.avatar_url} alt="hey therte " />
      </div>
<div>
{item.name}
</div>
<div style={{color:"grey"}}>
  @sachinPandey582
</div>

<div style={{width:"200px"}}>
Full-stack Developer | FOSS | JavaScript | Typescript | NodeJS | Deno | ReactJS | HTML | CSS | Chakra-UI | MUI
</div>
       </>
    ))
}
<Button bg={"green"}>Resume</Button> {" "}  {" "} {" "} {" "}
<Button bg={"red"}>Follow</Button>

    </div>
    <Projects/>
    <Experience/>
     
    </>
  )
}
export async function getStaticProps(){
  const res =await axios.get(`http://localhost:4004/values`)
  let value=await res.data
  
  console.log(value,"daat")
  return {
      props:{ users:value }
  }
}